# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainGUIfile(object):
    def setupUi(self, mainGUIfile):
        mainGUIfile.setObjectName("mainGUIfile")
        mainGUIfile.resize(449, 890)
        mainGUIfile.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(mainGUIfile)
        self.label.setGeometry(QtCore.QRect(0, -40, 451, 661))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../../../hp/speak.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(mainGUIfile)
        self.pushButton.setGeometry(QtCore.QRect(220, 840, 101, 41))
        self.pushButton.setStyleSheet("border-image: url(D:/Projects/contents/drive-download-20230413T081746Z-001/startb.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(mainGUIfile)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 840, 111, 41))
        self.pushButton_2.setStyleSheet("border-image: url(D:/Projects/contents/drive-download-20230413T081746Z-001/stopb.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(mainGUIfile)
        QtCore.QMetaObject.connectSlotsByName(mainGUIfile)

    def retranslateUi(self, mainGUIfile):
        _translate = QtCore.QCoreApplication.translate
        mainGUIfile.setWindowTitle(_translate("mainGUIfile", "mainGUIfile"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainGUIfile = QtWidgets.QWidget()
    ui = Ui_mainGUIfile()
    ui.setupUi(mainGUIfile)
    mainGUIfile.show()
    sys.exit(app.exec_())
